# Generated by Django 5.0 on 2023-12-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shared_to',
            field=models.JSONField(default=list),
        ),
    ]
